version: '3.7'
services:
  app:
    build: .
    image: akke_notify
    volumes:
      - .:/usr/src
    tmpfs:
      - /usr/src/tmp/pids
      - /usr/src/tmp/cache
      - /usr/src/tmp/
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - 3000:80
    command: rails s -b 0.0.0.0 -p 80
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


